language: node_js

node_js:
  - "8"
  - "10"

install:
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run build

deploy:
  on:
    branch: master
  provider: script
  skip_cleanup: true
  script:
    - npm run semantic-release && npm run styleguide:deploy --repo="https://${GH_TOKEN}@github.com/httpsOmkar/material-design-svelte.git"
